apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: testjava0319
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testjava0319 
  name: testjava0319
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testjava0319
    weight: 100 
